config/routes.rb
Rails.application.routes.draw do
  get 'mis_turnos/index'
  get 'perros/new'
  get 'perros/create'
  get 'user_search/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :campaigns, except: [:show] do
    member do
      delete :destroy
      post :pay
      get :pay # Permite solicitudes GET para la acción pay
    end
    collection do
      get :search
    end
  end

  resources :perros_perdidos, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_perdidos#mis_publicaciones'
      get 'filtrar', to: 'perros_perdidos#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_perdidos#mark_found'
    end
  end


get 'contactar_propietario', to: 'perros_perdidos#contactar_propietario'
#post 'enviar_correo', to: 'perros_perdidos#enviar_correo'
post 'enviar_correo_perdido', to: 'perros_perdidos#enviar_correo_perdido'


get 'contactar_propietario_encontrado', to: 'perros_encontrados#contactar_propietario_encontrado'
post 'enviar_correo_encontrado', to: 'perros_encontrados#enviar_correo_encontrado'

  resources :perros_encontrados, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_encontrados#mis_publicaciones'
      get 'filtrar', to: 'perros_encontrados#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_encontrados#mark_found', as: :mark_found
    end
  end

  
  

  Rails.application.routes.draw do
  get 'mis_turnos/index'
    


    resources :historial_turnos do
      collection do
        get 'confirmados', to: 'historial_turnos#confirmados', as: :turnos_confirmados
        get 'pendientes', to: 'historial_turnos#pendientes', as: :turnos_pendientes
        get 'hoy', to: 'historial_turnos#hoy', as: :turnos_hoy
        put 'cancelar_turno'
      end
      member do
        put 'cancelar_turno'
        put 'agregar_horario'
        put 'agregar_texto'
        put 'agregar_consulta'
        post 'create_vaccine'
      end
    end

    
  end

  get 'historial_turno/mis_turnos', to: 'mis_turnos#index', as: 'mis_turnos'

  get '/users/:id/perros', to: 'user_search#perros', as: 'user_perros'    
  resources :historial_turnos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'dashboard/perros_perdidos'
  get 'dashboard/solicitar_turno'
  get 'servicios/cuidadores'
  get 'dashboard/perros_encontrados'
  get 'dashboard/adopciones'
  get 'dashboard/cruza_de_perros'
  get 'servicios/paseadores'  
  get 'dashboard/iniciar_sesion'
  get 'dashboard/mi_usuario'
  get 'dashboard/registrar_perro'
  get 'dashboard/registrar_usuario'
  get 'dashboard/modificar_usuario'
  get 'dashboard/eliminar_usuario'
  get 'dashboard/index'
  get '/perros/mis_perros'
  get '/users/search', to: 'user_search#search'
  get '/perros/registrar_perro', to: 'perros#new', as: 'registrar_perro'
  get 'cruza/cruza'
  get 'cruza/publicar'
  get 'cruza/eliminar_perro'

  Rails.application.routes.draw do
    get 'eliminar_perro', to: 'cruza#eliminar_perro'
    delete 'eliminar_perro', to: 'cruza#destroy_perro_cruza'
    get 'cruza', to: 'cruza#cruza'
    get 'publicar', to: 'cruza#publicar'
    get 'mis_perros_cruza', to: 'cruza#mis_perros_cruza'
    get 'mis_perros_cruzados', to: 'cruza#mis_perros_cruzados'
  
    resources :cruza, only: [:destroy] do
      member do
        get 'contactar'
        delete 'destroy'
      end
    
      collection do
        post 'publicar', to: 'cruza#publicar', as: 'publicar'
      end
    end
  end


  get 'perros/editar_perro'
  get 'cargar_cuidador', to: 'servicios#cargar_cuidador', as: :cargar_cuidador
  get 'cargar_paseador', to: 'servicios#cargar_paseador', as: :cargar_paseador
  post '/guardar_cuidador', to: 'servicios#guardar_cuidador'
  post '/guardar_paseador', to: 'servicios#guardar_paseador'

  match '/enviar_correo', to: 'servicios#enviar_correo', via: [:post, :delete]


  get '/paseadores', to: 'servicios#paseadores', as: 'paseadores'
  get '/cuidadores', to: 'servicios#cuidadores', as: 'cuidadores'


  resources :servicios, except: [:show] do
    member do
      get 'edit'   # Página de edición
      patch 'actualizar_servicio'   # Acción de actualización
      delete 'destroy'  # Nueva acción para eliminar
    end
  end
resources :perros

  get 'mis_perros', to: 'perros#mis_perros', as: 'mis_perros'

  # config/routes.rb

  # config/routes.rb

  resources :usuarios, controller: 'dashboard', only: [] do
    member do
      patch :eliminar
    end
  end

  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password', as: 'edit_password_user'
    put 'users/update_password', to: 'users/registrations#update_password', as: 'update_password_user'
  end

  resources :user_search, only: [] do
    collection do
      get 'search'
    end
  end

  root "dashboard#index"


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def eliminar_usuario
    # Lógica para eliminar usuarios si es necesario
    # ...

    # Obtén la lista de usuarios habilitados
    @usuarios = User.where(habilitado: true)
  end

  # app/controllers/usuarios_controller.rb

def eliminar
  @usuario = User.find(params[:id])
  @usuario.update(habilitado: false)
  redirect_to root_path, notice: 'Usuario deshabilitado exitosamente.'
end

def registrar_perro
  dni = params[:dni_dueño] 
  @user = User.find_by(dni: dni)

  if @user
    @perro = Perro.new
    @perro.user = @user
  else
    flash[:alert] = 'User not found with the provided DNI'
    redirect_to root_path
  end
end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/adopciones.html.erb
adopciones bosteros cojidos 9/12

app/views/dashboard/cruza_de_perros.html.erb
boca muerto

app/views/dashboard/eliminar_usuario.html.erb
<!-- app/views/dashboard/eliminar_usuario.html.erb -->

<div class="container mt-5">
  <h1 class="text-center mb-4">Eliminar Usuario</h1>

  <div class="row justify-content-center">
    <div class="col-md-8"> <!-- Ajusta el tamaño de la columna según tus necesidades -->
      <div class="card">
        <div class="card-body p-4">

          <h2 class="text-center mb-4">Lista de Usuarios Habilitados</h2>

          <table class="table">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              <% @usuarios.each do |usuario| %>
                <tr>
                  <td><%= usuario.nombre %></td>
                  <td><%= usuario.apellido %></td>
                  <td><%= usuario.email %></td>
                  <td>
                    <%= form_tag(eliminar_usuario_path(usuario), method: :patch, class: 'user-form') do %>
                      <%= submit_tag 'Eliminar', class: 'btn btn-danger btn-block' %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Página de Inicio - Oh My Dog</title>
    <style>
        header {
            text-align: center;
            padding: 20px;
            background-color: #fc904f;
            color: #ffffff;
        }

        main {
            text-align: center;
            padding: 20px;
        }

        main img {
            max-width: 100%;
            height: auto;
        }

        /* Agregamos una clase deshabilitada */
        .disabled {
            pointer-events: none;
            opacity: 0.5; /* Puedes ajustar la opacidad según tus preferencias */
        }
    </style>
</head>
<body>

    <header>
        <h1>Bienvenido a la página de Oh My Dog</h1>
    </header>

    <main>
        <img src="<%= asset_path('logo.png') %>" alt="Logo de Oh My Dog">

        <div class="container mt-5">
            <div class="row justify-content-center">


                <!-- Tarjeta: Solicitar Turno -->
                <div class="col-md-2">
                    <div class="card">
                        <a href="<%= new_historial_turno_path %>" >
                            <img src="<%= asset_path('turno.png') %>" class="card-img-top" alt="Imagen de la opción">
                            <div class="card-body">
                                <h6 class="card-title">Solicitar Turno</h6>
                            </div>
                        </a>
                    </div>
                </div>

                <!-- Tarjeta: Perros Perdidos -->
                <div class="col-md-2">
                    <div class="card">
                        <%= link_to perros_perdidos_path, class: 'card-link' do %>
                            <img src="<%= asset_path('perro.png') %>" class="card-img-top" alt="Imagen de la opción">
                            <div class="card-body">
                                <h6 class="card-title">Perros Perdidos</h6>
                            </div>
                        <% end %>
                    </div>
                </div>


                <!-- Tarjeta: Perros Encontrados -->
               <div class="col-md-2">
                    <div class="card">
                        <%= link_to perros_encontrados_path, class: 'card-link' do %>
                            <img src="<%= asset_path('perro.png') %>" class="card-img-top" alt="Imagen de la opción">
                            <div class="card-body">
                                <h6 class="card-title">Perros Encontrados</h6>
                            </div>
                        <% end %>
                    </div>
                </div>


    

                <!-- Tarjeta: Paseadores -->
                <div class="col-md-2">
                    <div class="card">
                        <a href="/servicios/paseadores.html" >
                            <img src="<%= asset_path('paseador.png') %>" class="card-img-top" alt="Imagen de la opción">
                            <div class="card-body">
                                <h6 class="card-title">Paseadores</h6>
                            </div>
                        </a>
                    </div>
                </div>

                <!-- Tarjeta: Cuidadores -->
                <div class="col-md-2">
                    <div class="card">
                        <a href="/servicios/cuidadores.html" >
                            <img src="<%= asset_path('cuidador.png') %>" class="card-img-top" alt="Imagen de la opción">
                            <div class="card-body">
                                <h6 class="card-title">Cuidadores</h6>
                            </div>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </main>

</body>
</html>

app/views/dashboard/iniciar_sesion.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">DNI</label>
    <input type="integer" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Ingrese su DNI">
    <small id="emailHelp" class="form-text text-muted"></small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Contraseña">
  </div>

  <button type="submit" class="btn btn-primary">Entrar</button>

</form>

app/views/dashboard/mis_perros.html.erb
<!-- app/views/perros/mis_perros.html.erb -->

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center mb-4">Mis Perros</h1>

      <% if @mis_perros.present? %>
        <ul class="list-group">
          <% @mis_perros.each do |perro| %>
            <li class="list-group-item">
              <%= "Nombre: #{perro.nombre}, Edad: #{perro.edad}, Sexo: #{perro.sexo}" %>
              <!-- Puedes agregar más detalles según tus necesidades -->
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="mt-4">No tienes perros registrados.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/modificar_usuario.html.erb
<div class="text-center">
    <h1>Modificar usuarios</h1>
</div>

<form>


<!DOCTYPE html>
<html>
<head>
   <!DOCTYPE html>
<html>
<head>
    <!-- Encabezado del documento -->
</head>
<body>
    <form action="/procesar" method="post" id="registroForm">
      <div class="form-group">
      <label for="nombre">Nombre</label>
      <input type="email" class="form-control" id="nombre" placeholder="Ingrese su nombre.">
      </div>

      <div class="form-group">
    <label for="apellido">Apellido</label>
    <input type="email" class="form-control" id="apellido" placeholder="Ingrese su apellido.">
  </div>

  <form action="/procesar" method="post">
  <div class="form-group">
    <label for="fechaNacimiento">Fecha de Nacimiento:</label>
    <input type="date" id="fechaNacimiento" name="fechaNacimiento" class="form-control">
  </div>
</form>


  <div class="form-group">
    <label for="dni">DNI</label>
    <input type="text" class="form-control" id="dni" name="dni" pattern="[0-9]{8}" maxlength="8" placeholder="Ingrese su DNI" required>
</div>

  <form action="/procesar" method="post">
  <div class="form-group">
    <label for="email">Correo Electrónico:</label>
    <input type="email" id="email" name="email" class="form-control" placeholder="usuario@ejemplo.com">
  </div>
  </form>

        <div class="form-group">
            <label for="edad">Edad:</label>
            <input type="integer" id="edad" name="edad" class="form-control" required>
        </div>

        <!-- Agrega más campos aquí -->

        <button type="button" class="btn btn-primary mx-auto d-block" id="validarBoton">Registrar Usuario</button>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const formulario = document.getElementById('registroForm');
            const campoEdad = document.getElementById('edad');
            const campoNombre = document.getElementById('nombre');
            const campoApellido = document.getElementById('apellido');

            const botonValidar = document.getElementById('validarBoton');

            botonValidar.addEventListener('click', function () {
                const edad = parseInt(campoEdad.value);

                if (edad < 19) {
                    alert('Debes ser mayor de 18 años para registrarte.');
                    return;
                }

                // Agrega más validaciones para otros campos aquí
                if (campoNombre.value.trim() === '') {
                    alert('El campo Nombre es obligatorio.');
                    return;
                }

                if (campoApellido.value.trim() === '') {
                    alert('El campo Apellido es obligatorio.');
                    return;
                }

                // Si todas las validaciones pasan, envía el formulario
                formulario.submit();
            });
        });
    </script>
</body>
</html>


</form>

app/views/dashboard/perros_encontrados.html.erb
<!DOCTYPE html>
<html>
<head>
    <style>
        .card {
            display: flex;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 10px;
            padding: 10px;
            max-width: 400px; /* Establece el ancho máximo de la tarjeta */
            height: 200px; /* Establece la altura fija de la tarjeta */
        }

        .card img {
            max-width: 100%; /* Establece el ancho máximo de la imagen al 100% del contenedor */
            max-height: 100%; /* Establece la altura máxima de la imagen al 100% del contenedor */
            margin-right: 10px;
        }

        .card-content {
            flex: 1;
        }

        .card-title {
            font-weight: bold;
            font-size: 18px;
        }

        .card-description {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="card">
        <img src="<%= asset_path('perrodeprueba.jpeg') %>" alt="Imagen 1">
        <div class="card-content">
            <div class="card-title">Título de la Publicación 1</div>
            <div class="card-description">Descripción breve de la publicación 1. Aquí puedes incluir información adicional sobre el contenido de la publicación.</div>
        </div>
    </div>

    <div class="card">
        <img src="<%= asset_path('perrodeprueba.jpeg') %>" alt="Imagen 2">
        <div class="card-content">
            <div class="card-title">Título de la Publicación 2</div>
            <div class="card-description">Descripción breve de la publicación 2. Puedes personalizar este texto según tus necesidades.</div>
        </div>
    </div>
</body>
</html>

app/views/dashboard/perros_perdidos.html.erb
<!DOCTYPE html>
<html>
<head>
    <style>
        .card {
            display: flex;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 10px;
            padding: 10px;
            max-width: 400px; /* Establece el ancho máximo de la tarjeta */
            height: 200px; /* Establece la altura fija de la tarjeta */
        }

        .card img {
            max-width: 100%; /* Establece el ancho máximo de la imagen al 100% del contenedor */
            max-height: 100%; /* Establece la altura máxima de la imagen al 100% del contenedor */
            margin-right: 10px;
        }

        .card-content {
            flex: 1;
        }

        .card-title {
            font-weight: bold;
            font-size: 18px;
        }

        .card-description {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="card">
        <img src="<%= asset_path('perrodeprueba.jpeg') %>" alt="Imagen 1">
        <div class="card-content">
            <div class="card-title">Título de la Publicación 1</div>
            <div class="card-description">Descripción breve de la publicación 1. Aquí puedes incluir información adicional sobre el contenido de la publicación.</div>
        </div>
    </div>

    <div class="card">
        <img src="<%= asset_path('perrodeprueba.jpeg') %>" alt="Imagen 2">
        <div class="card-content">
            <div class="card-title">Título de la Publicación 2</div>
            <div class="card-description">Descripción breve de la publicación 2. Puedes personalizar este texto según tus necesidades.</div>
        </div>
    </div>
</body>
</html>

app/views/dashboard/registrar_perro.html.erb
<form>
<div class="text-center">
    <h1>Registro de perros</h1>
</div>

  <div class="form-group">
    <label for="exampleFormControlInput1">DNI del dueño</label>
    <input type="integer" class="form-control" id="exampleFormControlInput1" placeholder="EJ: 34543234">
  </div>
  <div class="form-group">
  <label for="exampleFormControlInput1">Nombre del perro</label>
  <input type="integer" class="form-control" id="exampleFormControlInput1" placeholder="EJ: Toby">
</div>
<div class="form-group">
  <label for="exampleFormControlInput1">Edad (en meses)</label>
  <input type="integer" class="form-control" id="exampleFormControlInput1" placeholder="EJ: 14">
</div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Raza</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>Labrador</option>
      <option>Bulldog</option>
      <option>Golden</option>
      <option>Pastor Aleman</option>
      <option>Caniche</option>
      <option>Pitbull</option>
    </select>
    </div>
    <div class="form-group">
    <label for="exampleFormControlSelect1">Sexo</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>Macho</option>
      <option>Hembra</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Color</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>Negro</option>
      <option>Blanco</option>
      <option>Rayado</option>
      <option>Gris</option>
      <option>Marrón</option>
    </select>
  </div>
  
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Historia médica</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
  </div>

  <h5>Subir una imagen</h5>
    <form action="procesar.php" method="post" enctype="multipart/form-data">
        <label for="imagen">Selecciona una imagen:</label>
        <input type="file" name="imagen" id="imagen" accept="image/*">
        <br>
        <input type="submit" value="Cargar Imagen">
    </form>

  <div>
  <button type="submit" class="btn btn-primary mx-auto d-block">Registrar Perro</button>
  </div>

</form>

app/views/dashboard/registrar_usuario.html.erb
<div class="text-center">
    <h1>Registro de usuarios</h1>
</div>

<form>


<!DOCTYPE html>
<html>
<head>
    <!-- Encabezado del documento -->
</head>
<body>
    <form action="/procesar" method="post" id="registroForm">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese su nombre." required>
        </div>
        
        <div class="form-group">
            <label for="apellido">Apellido</label>
            <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Ingrese su apellido." required>
        </div>

        <div class="form-group">
            <label for="fechaNacimiento">Fecha de Nacimiento:</label>
            <input type="date" id="fechaNacimiento" name="fechaNacimiento" class="form-control">
        </div>

        <div class="form-group">
            <label for "dni">DNI</label>
            <input type="number" class="form-control" id="dni" name="dni" pattern="[0-9]{8}" maxlength="8" placeholder="Ingrese su DNI" required>
        </div>

        <div class="form-group">
            <label for="email">Correo Electrónico:</label>
            <input type="email" id="email" name="email" class="form-control" placeholder="usuario@ejemplo.com">
        </div>


        <button type="button" class="btn btn-primary mx-auto d-block" id="registrarBoton" disabled>Registrar Usuario</button>
    </form>

    <script>
    document.addEventListener('DOMContentLoaded', function () {
        const formulario = document.getElementById('registroForm');
        const campoNombre = document.getElementById('nombre');
        const campoApellido = document.getElementById('apellido');
        const campoDNI = document.getElementById('dni');
        const campoEmail = document.getElementById('email');
        const campoFechaNacimiento = document.getElementById('fechaNacimiento');

        const botonRegistrar = document.getElementById('registrarBoton');

        // Función para verificar si los campos obligatorios están llenos
        function validarCamposObligatorios() {
            return (
                campoNombre.value.trim() !== '' &&
                campoApellido.value.trim() !== '' &&
                campoDNI.value.trim() !== '' &&
                campoEmail.value.trim() !== '' &&
                campoFechaNacimiento.value.trim() !== ''
            );
        }

        // Agregar eventos de escucha para los campos obligatorios
        campoNombre.addEventListener('input', validarFormulario);
        campoApellido.addEventListener('input', validarFormulario);
        campoDNI.addEventListener('input', validarFormulario);
        campoEmail.addEventListener('input', validarFormulario);
        campoFechaNacimiento.addEventListener('input', validarFormulario);

        // Función para validar el formulario
        function validarFormulario() {
            if (validarCamposObligatorios()) {
                    botonRegistrar.removeAttribute('disabled');
                }
            else {
                botonRegistrar.setAttribute('disabled', 'true');
            }
        }

        botonRegistrar.addEventListener('click', function () {
            if (!botonRegistrar.hasAttribute('disabled')) {
                const edad = calcularEdad(campoFechaNacimiento.value);
                if (edad >= 18) {
                    // Si todas las validaciones pasan, envía el formulario
                    formulario.submit();
                } else {
                    alert('Debes ser mayor de 18 años para registrarte.');
                }
            }
        });

        // Función para calcular la edad
        function calcularEdad(fechaNacimiento) {
            const hoy = new Date();
            const fechaNac = new Date(fechaNacimiento);
            let edad = hoy.getFullYear() - fechaNac.getFullYear();
            const mes = hoy.getMonth() - fechaNac.getMonth();
            if (mes < 0 || (mes === 0 && hoy.getDate() < fechaNac.getDate())) {
                edad--;
            }
            return edad;
        }
    });
</script>

</body>
</html>



</form>

app/views/dashboard/solicitar_turno.html.erb
<form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</form>

app/views/dashboard/turnos_confirmados.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- Estilos y otros encabezados aquí -->
</head>
<body>
<h1>DAsboard_turnosConfirmados</h1>
<% if @turnos_confirmados.present? %>
    <div class="card-container">
    <% @turnos_confirmados.each do |turno| %>
        <div class="card">
        <div class="card-content">
            <h5 class="card-title"><strong>Nombre:</strong> <%= turno.perro.nombre %></h5>
        </div>
        <div class="button-container">
            <!-- Botones y acciones relacionadas con cada turno -->
        </div>
        </div>
    <% end %>
    </div>
    <% else %>
    <p>No hay turnos confirmados.</p>
<% end %>

</body>
</html>