config/routes.rb
Rails.application.routes.draw do
  get 'mis_turnos/index'
  get 'perros/new'
  get 'perros/create'
  get 'user_search/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :campaigns, except: [:show] do
    member do
      delete :destroy
      post :pay
      get :pay # Permite solicitudes GET para la acción pay
    end
    collection do
      get :search
    end
  end

  resources :perros_perdidos, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_perdidos#mis_publicaciones'
      get 'filtrar', to: 'perros_perdidos#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_perdidos#mark_found'
    end
  end


get 'contactar_propietario', to: 'perros_perdidos#contactar_propietario'
#post 'enviar_correo', to: 'perros_perdidos#enviar_correo'
post 'enviar_correo_perdido', to: 'perros_perdidos#enviar_correo_perdido'


get 'contactar_propietario_encontrado', to: 'perros_encontrados#contactar_propietario_encontrado'
post 'enviar_correo_encontrado', to: 'perros_encontrados#enviar_correo_encontrado'

  resources :perros_encontrados, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_encontrados#mis_publicaciones'
      get 'filtrar', to: 'perros_encontrados#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_encontrados#mark_found', as: :mark_found
    end
  end

  
  

  Rails.application.routes.draw do
  get 'mis_turnos/index'
    


    resources :historial_turnos do
      collection do
        get 'confirmados', to: 'historial_turnos#confirmados', as: :turnos_confirmados
        get 'pendientes', to: 'historial_turnos#pendientes', as: :turnos_pendientes
        get 'hoy', to: 'historial_turnos#hoy', as: :turnos_hoy
        put 'cancelar_turno'
      end
      member do
        put 'cancelar_turno'
        put 'agregar_horario'
        put 'agregar_texto'
        put 'agregar_consulta'
        post 'create_vaccine'
      end
    end

    
  end

  get 'historial_turno/mis_turnos', to: 'mis_turnos#index', as: 'mis_turnos'

  get '/users/:id/perros', to: 'user_search#perros', as: 'user_perros'    
  resources :historial_turnos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'dashboard/perros_perdidos'
  get 'dashboard/solicitar_turno'
  get 'servicios/cuidadores'
  get 'dashboard/perros_encontrados'
  get 'dashboard/adopciones'
  get 'dashboard/cruza_de_perros'
  get 'servicios/paseadores'  
  get 'dashboard/iniciar_sesion'
  get 'dashboard/mi_usuario'
  get 'dashboard/registrar_perro'
  get 'dashboard/registrar_usuario'
  get 'dashboard/modificar_usuario'
  get 'dashboard/eliminar_usuario'
  get 'dashboard/index'
  get '/perros/mis_perros'
  get '/users/search', to: 'user_search#search'
  get '/perros/registrar_perro', to: 'perros#new', as: 'registrar_perro'
  get 'cruza/cruza'
  get 'cruza/publicar'
  get 'cruza/eliminar_perro'

  Rails.application.routes.draw do
    get 'eliminar_perro', to: 'cruza#eliminar_perro'
    delete 'eliminar_perro', to: 'cruza#destroy_perro_cruza'
    get 'cruza', to: 'cruza#cruza'
    get 'publicar', to: 'cruza#publicar'
    get 'mis_perros_cruza', to: 'cruza#mis_perros_cruza'
    get 'mis_perros_cruzados', to: 'cruza#mis_perros_cruzados'
  
    resources :cruza, only: [:destroy] do
      member do
        get 'contactar'
        delete 'destroy'
      end
    
      collection do
        post 'publicar', to: 'cruza#publicar', as: 'publicar'
      end
    end
  end


  get 'perros/editar_perro'
  get 'cargar_cuidador', to: 'servicios#cargar_cuidador', as: :cargar_cuidador
  get 'cargar_paseador', to: 'servicios#cargar_paseador', as: :cargar_paseador
  post '/guardar_cuidador', to: 'servicios#guardar_cuidador'
  post '/guardar_paseador', to: 'servicios#guardar_paseador'

  match '/enviar_correo', to: 'servicios#enviar_correo', via: [:post, :delete]


  get '/paseadores', to: 'servicios#paseadores', as: 'paseadores'
  get '/cuidadores', to: 'servicios#cuidadores', as: 'cuidadores'


  resources :servicios, except: [:show] do
    member do
      get 'edit'   # Página de edición
      patch 'actualizar_servicio'   # Acción de actualización
      delete 'destroy'  # Nueva acción para eliminar
    end
  end
resources :perros

  get 'mis_perros', to: 'perros#mis_perros', as: 'mis_perros'

  # config/routes.rb

  # config/routes.rb

  resources :usuarios, controller: 'dashboard', only: [] do
    member do
      patch :eliminar
    end
  end

  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password', as: 'edit_password_user'
    put 'users/update_password', to: 'users/registrations#update_password', as: 'update_password_user'
  end

  resources :user_search, only: [] do
    collection do
      get 'search'
    end
  end

  root "dashboard#index"


end

app/models/servicio.rb
class Servicio < ApplicationRecord
    validates :dni, uniqueness: { scope: [:tipo, :habilitado], message: "ya está registrado como paseador" }, if: -> { tipo == "2" && habilitado == 0 }
    validates :mail, uniqueness: { scope: [:tipo, :habilitado], message: "ya está registrado como paseador" }, if: -> { tipo == "2" && habilitado == 0 }
    validates :dni, uniqueness: { scope: [:tipo, :habilitado], message: "ya está registrado como cuidador" }, if: -> { tipo == "1" && habilitado == 0 }
    validates :mail, uniqueness: { scope: [:tipo, :habilitado], message: "ya está registrado como cuidador" }, if: -> { tipo == "1" && habilitado == 0 }
  end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:edit, :actualizar_servicio]
  skip_before_action :verify_authenticity_token, only: :enviar_correo
  def guardar_cuidador
    nombre = params[:nombre]
    apellido = params[:apellido]
    zona = params[:zona]
    horarios = params[:horarios]
    dni = params[:dni]
    mail = params[:mail]

    servicio = Servicio.new(
      nombre: nombre,
      apellido: apellido,
      zona: zona,
      horarios: horarios,
      dni: dni,
      mail: mail,
      habilitado: 0,
      tipo: "1" 
    )
    if servicio.save
      flash[:success] = "Cuidador guardado exitosamente"
      redirect_to cuidadores_path
    else
      flash[:error] = "Error al guardar el cuidador"
      @errores = servicio.errors.full_messages
      render :cargar_cuidador
    end
  end

  def destroy
    @servicio = Servicio.find(params[:id])
    @servicio.update(habilitado: 1)
    redirect_to request.referer, notice: "Servicio eliminado exitosamente."
  end


  def cuidadores
    @servicios = Servicio.where(tipo: "1", habilitado: 0)
  end

  def paseadores
    @servicios = Servicio.where(tipo: "2", habilitado: 0)
  end

  def guardar_paseador
    # Recuperar los datos del formulario
    nombre = params[:nombre]
    apellido = params[:apellido]
    zona = params[:zona]
    horarios = params[:horarios]
    dni = params[:dni]
    mail = params[:mail]

    # Crear un nuevo objeto Servicio con los datos del formulario
    servicio = Servicio.new(
      nombre: nombre,
      apellido: apellido,
      zona: zona,
      horarios: horarios,
      dni: dni,
      mail: mail,
      habilitado: 0,
      tipo: "2"  # Asignar "2" para indicar que es un paseador
    )

    # Guardar el objeto en la base de datos
    if servicio.save
      flash[:success] = "Paseador guardado exitosamente"
      redirect_to paseadores_path
    else
      flash[:error] = "Error al guardar el Paseador"
      @errores = servicio.errors.full_messages
      render :cargar_paseador
    end
  end

  def enviar_correo
    @user_email = params['user-email']
    @paseador_email = params['paseador-email']
    @servicio_tipo = params['servicio-tipo']

    if @servicio_tipo == '1'
      UserMailer.contacto(@user_email, @paseador_email).deliver_now
    else @servicio_tipo == '2'
      UserMailer.contacto_paseador(@user_email, @paseador_email).deliver_now
    end

    
    redirect_back(fallback_location: root_path)
  end

  def actualizar_servicio
    # Validar la unicidad de DNI y correo electrónico solo si cambian
    if @servicio.dni != servicio_params[:dni] && Servicio.exists?(dni: servicio_params[:dni], tipo: @servicio.tipo, habilitado: 0)
      @servicio.errors.add(:dni, "ya está registrado como paseador") if @servicio.tipo == "2"
      @servicio.errors.add(:dni, "ya está registrado como cuidador") if @servicio.tipo == "1"
    end
  
    if @servicio.mail != servicio_params[:mail] && Servicio.exists?(mail: servicio_params[:mail], tipo: @servicio.tipo, habilitado: 0)
      @servicio.errors.add(:mail, "ya está registrado como paseador") if @servicio.tipo == "2"
      @servicio.errors.add(:mail, "ya está registrado como cuidador") if @servicio.tipo == "1"
    end
  
    if @servicio.errors.empty? && @servicio.update(servicio_params)
      flash[:success] = "Servicio actualizado exitosamente"
      if (@servicio.tipo == "2")
        redirect_to paseadores_path
      else
        redirect_to cuidadores_path
      end
    else
      flash[:error] = "Error al actualizar el servicio"
      render :edit
    end
  end

  private

  def servicio_params
    params.require(:servicio).permit(:nombre, :apellido, :dni, :zona, :mail, :tipo, :horarios, :habilitado)
  end

  def set_servicio
    @servicio = Servicio.find(params[:id])
  end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/cuidadores.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= csrf_meta_tags %>
  <style>
      body {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
      }

      .container {
          text-align: center;
          padding-bottom: 60px; /* Ajuste para dejar espacio para el footer */
      }

      .title {
          font-size: 24px;
          font-weight: bold;
          margin-bottom: 20px;
      }

      .card-container {
          display: flex;
          flex-wrap: wrap;
          justify-content: space-between;
          margin-top: 10px;
          text-align: left;
      }
      .card {
          flex: 0 0 calc(45% - 20px);
          border: 1px solid #ddd;
          border-radius: 5px;
          margin: 10px;
          padding: 15px;
          min-height: 180px;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          position: relative; /* Agregado para posicionar los botones */
      }

      .card-header {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          padding: 10px;
      }

      .card-title {
          font-weight: bold;
          font-size: 18px;
      }

      .card-description {
          font-size: 14px;
      }

      .options-button,
      .contact-button,
      .become-caretaker-button,
      .edit-button,
      .delete-button {
          padding: 10px;
          margin: 5px;
          border: 1px solid #333;
          border-radius: 5px;
          cursor: pointer;
      }

      .options-container {
          position: absolute;
          bottom: 5px;
          right: 5px;
          background-color: #fff;
          border: 1px solid #ddd;
          border-radius: 3px;
          display: none;
          flex-direction: column;
          z-index: 1; /* Coloca el contenedor de opciones encima de las tarjetas */
          animation: slideIn 0.3s ease-out; /* Animación de entrada */
      }

      .card-content {
          flex: 1;
          display: flex;
          flex-direction: column;
      }

      .button-container {
          display: flex;
          justify-content: space-between; /* Cambiado a space-between para separar los botones */
      }

      .options-button,
      .delete-button,
      .edit-button {
          padding: 10px;
          margin: 5px;
          border: 1px solid #333;
          border-radius: 5px;
          cursor: pointer;
      }

      .contact-button,
      .become-caretaker-button {
          padding: 10px;
          margin: 5px;
          border: 1px solid #333;
          border-radius: 5px;
          cursor: pointer;
      }

      .edit-button {
          padding: 10px;
          margin: 5px;
          border: 1px solid #333;
          border-radius: 5px;
          cursor: pointer;
      }

      /* Footer styles */
      .footer {
          position: fixed;
          bottom: 0;
          width: 100%;
          background-color: #f1f1f1;
          padding: 10px 0;
          text-align: center;
      }

      #filtro-form button {
          background-color: #fc904f; /* Color de fondo verde */
          color: white; /* Texto blanco */
          padding: 10px 20px; /* Espaciado interno */
          border: none; /* Sin borde */
          border-radius: 5px; /* Bordes redondeados */
          cursor: pointer; /* Cursor apuntador */
      }

      #filtro-form button:hover {
          background-color: #bd622a; /* Cambio de color al pasar el ratón */
      }


      .button-group {
              display: flex;
          }

      /* Animación de entrada */
      @keyframes slideIn {
          from {
              opacity: 0;
              transform: translateY(-10px);
          }
          to {
              opacity: 1;
              transform: translateY(0);
          }
      }
  </style>
</head>
<body>
    <div class="container">
        <div class="title">Listado de Cuidadores</div>

        <% if user_signed_in? && current_user.rol_id == 1 %>
            <div class="button-container">
                <button class="become-caretaker-button" onclick="window.location.href='<%= cargar_cuidador_path %>'">Cargar Cuidador</button>
            </div>
        <% end %>

        <form id="filtro-form">
            <label for="filtro-zona">Filtrar por Zona:</label>
            <select id="filtro-zona" name="filtro-zona">
                <option value="">Todos</option>
                <option value="plaza-san-martin">Plaza San Martín</option>
                <option value="plaza-moreno">Plaza Moreno</option>
                <option value="plaza-azcuenaga">Plaza Azcuénaga</option>
                <option value="plaza-belgrano">Plaza Belgrano</option>
                <option value="parque-saavedra">Parque Saavedra</option>
                <option value="parque-castelli">Parque Castelli</option>
                <option value="Plaza-Malvinas-Argentinas">Plaza Malvinas Argentinas</option>
                <option value="plaza-rivadavia">Plaza Rivadavia</option>
                <option value="parque-vucetich">Parque Vucetich</option>
                <option value="plaza-rocha">Plaza Rocha</option>
                <option value="plaza-italia">Plaza Italia</option>
                <option value="plaza-matheu">Plaza Matheu</option>
                <option value="plaza-espana">Plaza España</option>
                <option value="plaza-sarmiento">Plaza Sarmiento</option>
                <option value="plaza-paso">Plaza Paso</option>
            </select>
            <button type="button" onclick="filtrarPorZona()">Filtrar</button>
        </form>

        <% if @servicios.present? %>
        <div class="card-container">
            <% @servicios.each do |servicio| %>
                <% if servicio.tipo == "1" && servicio.habilitado == 0 %>
                    <div class="card <%= servicio.zona.present? ? servicio.zona.parameterize : '' %>">
                        <div class="card-content">
                            <div class="card-title">Nombre: <%= servicio.nombre %> <%= servicio.apellido %></div>
                            <div class="card-description">Zona: <%= servicio.zona %></div>
                            <div class="card-description">Disponibilidad: <%= servicio.horarios %></div>
                        </div>
                        <div id="contact-form-<%= servicio.id %>" class="button-container">
                            <form action="<%= enviar_correo_path %>" method="post">
                                <%= csrf_meta_tags %>
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                                <label for="user-email">Tu correo electrónico:</label>
                                <% if user_signed_in? %>     
                                    <input type="email" id="user-email-<%= servicio.id %>" name="user-email" value="<%= current_user.email %>" required>
                                <% else %>
                                    <input type="email" id="user-email-<%= servicio.id %>" name="user-email" required>
                                <% end %>
                                <input type="hidden" name="paseador-email" value="<%= servicio.mail %>">
                                <input type="hidden" name="servicio-id" value="<%= servicio.id %>">
                                <input type="hidden" name="servicio-tipo" value="<%= servicio.tipo %>">
                                <button type="submit" class="edit-button">Contactar</button>
                            </form>
                        </div>
                        <% if user_signed_in? && current_user.rol_id == 1 %>
                            <div class="button-group">
                                <button type="button" class="edit-button" onclick="window.location.href='<%= edit_servicio_path(servicio) %>'">Editar</button>
                                <%= form_for(servicio, method: :delete, url: servicio_path(servicio)) do |f| %>
                                    <%= csrf_meta_tags %>
                                    <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
                                    <%= f.submit "Eliminar", class: "delete-button" %>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>
        <% else %>
            <p>No hay cuidadores disponibles.</p>
        <% end %>

        <div id="mensaje-servicios" class="mensaje-servicios"></div>

        <script>
            function filtrarPorZona() {
                var zonaSeleccionada = document.getElementById('filtro-zona').value;

                // Lógica de filtrado
                var cards = document.querySelectorAll('.card');
                var serviciosEncontrados = false;

                cards.forEach(function (card) {
                    // Verifica si la tarjeta tiene la clase de la zona seleccionada
                    if (zonaSeleccionada === '' || card.classList.contains(zonaSeleccionada)) {
                        card.style.display = 'flex';
                        serviciosEncontrados = true;
                    } else {
                        card.style.display = 'none';
                    }
                });

                // Muestra el mensaje si no se encuentran servicios
                var mensajeServicios = document.getElementById('mensaje-servicios');
                if (!serviciosEncontrados) {
                    mensajeServicios.textContent = "No hay cuidadores en esa zona";
                } else {
                    mensajeServicios.textContent = ""; // Limpiar el mensaje si se encuentran servicios
                }
            }
        </script>

    </body>

</html>

app/views/servicios/edit.html.erb
<% if @servicio.errors.any? %>
  <div class="alert alert-danger">
    <p>Hubo errores al guardar el Paseador:</p>
    <ul>
      <% @servicio.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-5">
      <div class="card">
        <div class="card-body p-4">
          <h2 class="text-center mb-4">Editar Servicio</h2>

          <%= form_with(model: @servicio, url: actualizar_servicio_servicio_path(@servicio), method: 'patch', class: 'servicio-form') do |form| %>
            <div class="field">
              <%= form.label :nombre, class: "form-label" %>
              <%= form.text_field :nombre, class: 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :apellido, class: "form-label" %>
              <%= form.text_field :apellido, class: 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :mail, class: "form-label" %>
              <%= form.email_field :mail, class: 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :zona, class: "form-label" %>
              <%= form.select :zona, options_for_select(['Plaza San Martín', 'Plaza Moreno', 'Plaza Azcuénaga', 'Plaza Belgrano', 'Parque Saavedra', 'Parque Castelli', 'Plaza Malvinas Argentinas', 'Plaza Rivadavia', 'Parque Vucetich', 'Plaza Rocha', 'Plaza Italia', 'Plaza Matheu', 'Plaza España', 'Plaza Sarmiento','Plaza Paso']), { prompt: 'Seleccione una zona' }, { class: 'form-control' } %>
            </div>

            <div class="field">
              <%= form.label :horarios, class: "form-label" %>
              <%= form.text_area :horarios, class: 'form-control' %>
            </div>

            <div class="text-center">
              <%= form.submit 'Guardar', class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/servicios/paseadores.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= csrf_meta_tags %>
    <style>
        body {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        .container {
            text-align: center;
            padding-bottom: 60px; /* Ajuste para dejar espacio para el footer */
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            margin-top: 10px;
            text-align: left;
        }
        .card {
            flex: 0 0 calc(45% - 20px);
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 10px;
            padding: 15px;
            min-height: 180px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            position: relative; /* Agregado para posicionar los botones */
        }

        .card-header {
            display: flex;
            justify-content: space-between;
            align-items: baseline;
            padding: 10px;
        }

        .card-title {
            font-weight: bold;
            font-size: 18px;
        }

        .card-description {
            font-size: 14px;
        }

        .options-button,
        .contact-button,
        .become-paseador-button,
        .edit-button,
        .delete-button {
            padding: 10px;
            margin: 5px;
            border: 1px solid #333;
            border-radius: 5px;
            cursor: pointer;
        }

        .options-container {
            position: absolute;
            bottom: 5px;
            right: 5px;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 3px;
            display: none;
            flex-direction: column;
            z-index: 1; /* Coloca el contenedor de opciones encima de las tarjetas */
            animation: slideIn 0.3s ease-out; /* Animación de entrada */
        }

        .card-content {
            flex: 1;
            display: flex;
            flex-direction: column;
        }

        .button-container {
            display: flex;
            justify-content: space-between; /* Cambiado a space-between para separar los botones */
        }

        .options-button,
        .delete-button,
        .edit-button {
            padding: 10px;
            margin: 5px;
            border: 1px solid #333;
            border-radius: 5px;
            cursor: pointer;
        }

        .contact-button,
        .become-paseador-button {
            padding: 10px;
            margin: 5px;
            border: 1px solid #333;
            border-radius: 5px;
            cursor: pointer;
        }

        .edit-button {
            padding: 10px;
            margin: 5px;
            border: 1px solid #333;
            border-radius: 5px;
            cursor: pointer;
        }

        /* Footer styles */
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #f1f1f1;
            padding: 10px 0;
            text-align: center;
        }

        #filtro-form button {
            background-color: #fc904f; /* Color de fondo verde */
            color: white; /* Texto blanco */
            padding: 10px 20px; /* Espaciado interno */
            border: none; /* Sin borde */
            border-radius: 5px; /* Bordes redondeados */
            cursor: pointer; /* Cursor apuntador */
        }

        #filtro-form button:hover {
            background-color: #bd622a; /* Cambio de color al pasar el ratón */
        }


        .button-group {
                display: flex;
            }

        /* Animación de entrada */
        @keyframes slideIn {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="title">Listado de Paseadores</div>

        <% if user_signed_in? && current_user.rol_id == 1 %>
            <div class="button-container">
                <button class="become-paseador-button" onclick="window.location.href='<%= cargar_paseador_path %>'">Cargar Paseador</button>
            </div>
        <% end %>

        <form id="filtro-form">
            <label for="filtro-zona">Filtrar por Zona:</label>
            <select id="filtro-zona" name="filtro-zona">
                <option value="">Todos</option>
                <option value="plaza-san-martin">Plaza San Martín</option>
                <option value="plaza-moreno">Plaza Moreno</option>
                <option value="plaza-azcuenaga">Plaza Azcuénaga</option>
                <option value="plaza-belgrano">Plaza Belgrano</option> 
                <option value="parque-saavedra">Parque Saavedra</option>
                <option value="parque-castelli">Parque Castelli</option>
                <option value="Plaza-Malvinas-Argentinas">Plaza Malvinas Argentinas</option>
                <option value="plaza-rivadavia">Plaza Rivadavia</option>
                <option value="parque-vucetich">Parque Vucetich</option>
                <option value="plaza-rocha">Plaza Rocha</option>
                <option value="plaza-italia">Plaza Italia</option>
                <option value="plaza-matheu">Plaza Matheu</option>
                <option value="plaza-espana">Plaza España</option>
                <option value="plaza-sarmiento">Plaza Sarmiento</option>
                <option value="plaza-paso">Plaza Paso</option>
            </select>
            <button type="button" onclick="filtrarPorZona()">Filtrar</button>
        </form>

        <% if @servicios.present? %>
        <div class="card-container">
            <% @servicios.each do |servicio| %>
                <% if servicio.tipo == "2" && servicio.habilitado == 0 %>
                    <div class="card <%= servicio.zona.present? ? servicio.zona.parameterize : '' %>">
                        <div class="card-content">
                            <div class="card-title">Nombre: <%= servicio.nombre %> <%= servicio.apellido %></div>
                            <div class="card-description">Zona: <%= servicio.zona %></div>
                            <div class="card-description">Disponibilidad: <%= servicio.horarios %></div>
                        </div>
                        <div id="contact-form-<%= servicio.id %>" class="button-container">
                            <form action="<%= enviar_correo_path %>" method="post">
                                <%= csrf_meta_tags %>
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                                <label for="user-email">Tu correo electrónico:</label>
                                <% if user_signed_in? %>     
                                    <input type="email" id="user-email-<%= servicio.id %>" name="user-email" value="<%= current_user.email %>" required>
                                <% else %>
                                    <input type="email" id="user-email-<%= servicio.id %>" name="user-email" required>
                                <% end %>
                                <input type="hidden" name="paseador-email" value="<%= servicio.mail %>">
                                <input type="hidden" name="servicio-id" value="<%= servicio.id %>">
                                <input type="hidden" name="servicio-tipo" value="<%= servicio.tipo %>">
                                <button type="submit" class="edit-button">Contactar</button>
                            </form>
                        </div>
                        <% if user_signed_in? && current_user.rol_id == 1 %>
                            <div class="button-group">
                                <button type="button" class="edit-button" onclick="window.location.href='<%= edit_servicio_path(servicio) %>'">Editar</button>
                                <%= form_for(servicio, method: :delete, url: servicio_path(servicio)) do |f| %>
                                    <%= csrf_meta_tags %>
                                    <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
                                    <%= f.submit "Eliminar", class: "delete-button" %>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            <% end %>
        </div>
        
        
        <% else %>
        <p>No hay paseadores disponibles.</p>
        <% end %>

        <div id="mensaje-servicios" class="mensaje-servicios"></div>

        <script>
            function filtrarPorZona() {
              var zonaSeleccionada = document.getElementById('filtro-zona').value;
              // Lógica de filtrado
              var cards = document.querySelectorAll('.card');
              var serviciosEncontrados = false;
              cards.forEach(function (card) {
                // Verifica si la tarjeta tiene la clase de la zona seleccionada
                if (zonaSeleccionada === '' || card.classList.contains(zonaSeleccionada)) {
                  card.style.display = 'flex';
                  serviciosEncontrados = true;
                } else {
                  card.style.display = 'none';
                }
              });
              // Muestra el mensaje si no se encuentran servicios
              var mensajeServicios = document.getElementById('mensaje-servicios');
              if (!serviciosEncontrados) {
                mensajeServicios.textContent = "No hay paseadores en esa zona";
              } else {
                mensajeServicios.textContent = ""; // Limpiar el mensaje si se encuentran servicios
              }
            }
        </script>
    </body>
</html>