config/routes.rb
Rails.application.routes.draw do
  get 'mis_turnos/index'
  get 'perros/new'
  get 'perros/create'
  get 'user_search/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :campaigns, except: [:show] do
    member do
      delete :destroy
      post :pay
      get :pay # Permite solicitudes GET para la acción pay
    end
    collection do
      get :search
    end
  end

  resources :perros_perdidos, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_perdidos#mis_publicaciones'
      get 'filtrar', to: 'perros_perdidos#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_perdidos#mark_found'
    end
  end


get 'contactar_propietario', to: 'perros_perdidos#contactar_propietario'
#post 'enviar_correo', to: 'perros_perdidos#enviar_correo'
post 'enviar_correo_perdido', to: 'perros_perdidos#enviar_correo_perdido'


get 'contactar_propietario_encontrado', to: 'perros_encontrados#contactar_propietario_encontrado'
post 'enviar_correo_encontrado', to: 'perros_encontrados#enviar_correo_encontrado'

  resources :perros_encontrados, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_encontrados#mis_publicaciones'
      get 'filtrar', to: 'perros_encontrados#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_encontrados#mark_found', as: :mark_found
    end
  end

  
  

  Rails.application.routes.draw do
  get 'mis_turnos/index'
    


    resources :historial_turnos do
      collection do
        get 'confirmados', to: 'historial_turnos#confirmados', as: :turnos_confirmados
        get 'pendientes', to: 'historial_turnos#pendientes', as: :turnos_pendientes
        get 'hoy', to: 'historial_turnos#hoy', as: :turnos_hoy
        put 'cancelar_turno'
      end
      member do
        put 'cancelar_turno'
        put 'agregar_horario'
        put 'agregar_texto'
        put 'agregar_consulta'
        post 'create_vaccine'
      end
    end

    
  end

  get 'historial_turno/mis_turnos', to: 'mis_turnos#index', as: 'mis_turnos'

  get '/users/:id/perros', to: 'user_search#perros', as: 'user_perros'    
  resources :historial_turnos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'dashboard/perros_perdidos'
  get 'dashboard/solicitar_turno'
  get 'servicios/cuidadores'
  get 'dashboard/perros_encontrados'
  get 'dashboard/adopciones'
  get 'dashboard/cruza_de_perros'
  get 'servicios/paseadores'  
  get 'dashboard/iniciar_sesion'
  get 'dashboard/mi_usuario'
  get 'dashboard/registrar_perro'
  get 'dashboard/registrar_usuario'
  get 'dashboard/modificar_usuario'
  get 'dashboard/eliminar_usuario'
  get 'dashboard/index'
  get '/perros/mis_perros'
  get '/users/search', to: 'user_search#search'
  get '/perros/registrar_perro', to: 'perros#new', as: 'registrar_perro'
  get 'cruza/cruza'
  get 'cruza/publicar'
  get 'cruza/eliminar_perro'

  Rails.application.routes.draw do
    get 'eliminar_perro', to: 'cruza#eliminar_perro'
    delete 'eliminar_perro', to: 'cruza#destroy_perro_cruza'
    get 'cruza', to: 'cruza#cruza'
    get 'publicar', to: 'cruza#publicar'
    get 'mis_perros_cruza', to: 'cruza#mis_perros_cruza'
    get 'mis_perros_cruzados', to: 'cruza#mis_perros_cruzados'
  
    resources :cruza, only: [:destroy] do
      member do
        get 'contactar'
        delete 'destroy'
      end
    
      collection do
        post 'publicar', to: 'cruza#publicar', as: 'publicar'
      end
    end
  end


  get 'perros/editar_perro'
  get 'cargar_cuidador', to: 'servicios#cargar_cuidador', as: :cargar_cuidador
  get 'cargar_paseador', to: 'servicios#cargar_paseador', as: :cargar_paseador
  post '/guardar_cuidador', to: 'servicios#guardar_cuidador'
  post '/guardar_paseador', to: 'servicios#guardar_paseador'

  match '/enviar_correo', to: 'servicios#enviar_correo', via: [:post, :delete]


  get '/paseadores', to: 'servicios#paseadores', as: 'paseadores'
  get '/cuidadores', to: 'servicios#cuidadores', as: 'cuidadores'


  resources :servicios, except: [:show] do
    member do
      get 'edit'   # Página de edición
      patch 'actualizar_servicio'   # Acción de actualización
      delete 'destroy'  # Nueva acción para eliminar
    end
  end
resources :perros

  get 'mis_perros', to: 'perros#mis_perros', as: 'mis_perros'

  # config/routes.rb

  # config/routes.rb

  resources :usuarios, controller: 'dashboard', only: [] do
    member do
      patch :eliminar
    end
  end

  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password', as: 'edit_password_user'
    put 'users/update_password', to: 'users/registrations#update_password', as: 'update_password_user'
  end

  resources :user_search, only: [] do
    collection do
      get 'search'
    end
  end

  root "dashboard#index"


end

app/controllers/perros_perdidos_controller.rb
# app/controllers/perros_perdidos_controller.rb
class PerrosPerdidosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit]
  protect_from_forgery with: :exception

  def index
    @perros_perdido = PerroPerdido.where(activa: true, tipo: 1) 
  end

  def new
    @user_perros = current_user.perros
    @perro_details = @user_perros.each_with_object({}) do |perro, details|
      details[perro.id] = { nombre: perro.nombre, raza_id: perro.raza_id, sexo: perro.sexo, fecha_nacimiento: perro.fecha_nacimiento, edad: ((Date.today - perro.fecha_nacimiento) / 30).to_i }
    end
    @perro_perdido = PerroPerdido.new
  end

  def mis_publicaciones
    @perros_perdido = PerroPerdido.where(user_id: current_user.id, tipo: 1)
    render 'index'
  end

  def filtrar
    if params[:filter_raza].present?
      @perros_perdido = PerroPerdido.where(raza_id: params[:filter_raza], activa: true, tipo: 1)
    else
      @perros_perdido = PerroPerdido.where(activa: true, tipo: 1)
    end
    render 'index'
  end

  def mark_found
    @perro_perdido = PerroPerdido.find(params[:id])
    @perro_perdido.update(encontrado: true)
    redirect_to perros_perdidos_path, notice: 'Perro marcado como encontrado.'
  end

  def update
    @perro_perdido = PerroPerdido.find(params[:id])

    if @perro_perdido.update(perro_perdido_params)
      redirect_to perros_perdidos_path, notice: 'Publicación actualizada exitosamente.'
    else
      render :edit
    end
  end

  def edit
    @perro_perdido = PerroPerdido.find(params[:id])
  end

  def contactar_propietario
    @perro_perdido = PerroPerdido.find(params[:id])

    render 'contactar_propietario'
  end

  def enviar_correo_perdido
    perro_perdido = PerroPerdido.find(params[:perro_id])
    correo_contacto = params[:correo]
    nombre = params[:nombre]
    telefono = params[:telefono]
  
    UserMailer.contactar_propietario_perdido(perro_perdido, correo_contacto, nombre, telefono).deliver_now
  
    redirect_to perros_perdidos_path, notice: 'Correo enviado con éxito. El dueño se contactará contigo vía mail.'
  end
  

  def destroy
    @perro_perdido = PerroPerdido.find(params[:id])

    if @perro_perdido
      @perro_perdido.update(activa: false)
      redirect_to perros_perdidos_path, notice: 'Publicación eliminada exitosamente.'
    else
      redirect_to perros_perdidos_path, alert: 'No se pudo encontrar la publicación.'
    end
  end

  def create
    @perro_perdido = PerroPerdido.new(perro_perdido_params)
    @perro_perdido.user_id = current_user.id
  
    # Calcular la edad en meses
    if @perro_perdido.fecha_nacimiento.present?
      @perro_perdido.edad = ((Date.today - @perro_perdido.fecha_nacimiento) / 30).to_i
    end
  
    if @perro_perdido.save
      redirect_to perros_perdidos_path, notice: 'La publicación de perro perdido fue creada exitosamente.'
    else
      render :new
    end
  end
  

  private

  def perro_perdido_params
    params.require(:perro_perdido).permit(:nombre, :sexo, :raza_id, :comportamiento, :lugar, :fecha, :foto, :edad, :mail, :tipo, :fecha_nacimiento)
  end
end

app/helpers/perros_perdidos_helper.rb
module PerrosPerdidosHelper
end

app/views/perros_perdidos/contactar_propietario.html.erb
<!-- app/views/perros_perdidos/contactar_propietario.html.erb -->
<div class="container text-center mt-5">
  <h1 class="mb-4">Contactar al Dueño</h1>

<%= form_with(url: enviar_correo_perdido_path, method: :post, class: 'contacto-form') do |form| %>
    <% if user_signed_in? %>
      <div class="form-group">
        <%= form.label :nombre, "Tu nombre" %>
        <%= form.text_field :nombre, class: 'form-control', required: true, value: current_user.nombre %>
      </div>

      <div class="form-group">
        <%= form.label :correo, "Tu correo de contacto" %>
        <%= form.email_field :correo, class: 'form-control', required: true, value: current_user.email%>
      </div>
    <% else %>
      <div class="form-group">
        <%= form.label :nombre, "Tu nombre" %>
        <%= form.text_field :nombre, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= form.label :correo, "Tu correo de contacto" %>
        <%= form.email_field :correo, class: 'form-control', required: true %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :telefono, "Tu número de teléfono" %>
      <%= form.telephone_field :telefono, class: 'form-control', required: true %>
    </div>

    <%= form.hidden_field :perro_id, value: @perro_perdido.id %>

    <div class="form-group">
      <%= form.submit "Enviar Correo", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/perros_perdidos/edit.html.erb
<!-- app/views/perros_perdidos/edit.html.erb -->
<div class="container mt-5">
  <h1 class="text-center">Editar Perro Perdido</h1>

<%= form_for @perro_perdido, url: perros_perdido_path(@perro_perdido), method: :patch, html: { class: 'my-4' } do |form| %>
    <% if @perro_perdido.errors.any? %>
      <div id="error_explanation" class="text-center">
        <h2><%= pluralize(@perro_perdido.errors.count, "error") %> prohibited this dog from being saved:</h2>
        <ul>
          <% @perro_perdido.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :nombre, class: 'form-label' %>
      <%= form.text_field :nombre, class: 'form-control', placeholder: 'Nombre del perro', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :sexo, class: "form-label" %>
      <%= form.select :sexo, ["Macho", "Hembra"], { prompt: "Seleccionar Sexo" }, { class: "form-control", id: "sexo_perro" } %>
    </div>

    <div class="mb-3">
      <%= form.label :raza_id, "Raza" %>
      <%= form.collection_select :raza_id, Raza.all, :id, :nombre, { prompt: "Seleccione una raza" }, class: "form-control", id: "raza_perro" %>
    </div>

    <div class="mb-3">
      <%= form.label :comportamiento, class: 'form-label' %>
      <%= form.text_area :comportamiento, class: 'form-control', placeholder: 'Comportamiento del perro' %>
    </div>

    <div class="mb-3">
      <%= form.label :lugar, class: 'form-label' %>
      <%= form.text_field :lugar, class: 'form-control', placeholder: 'Lugar donde se perdió' %>
    </div>

    <div class="mb-3">
      <%= form.label :fecha, "Ultima vez que se vió", class: 'form-label' %>
      <%= form.date_field :fecha, class: 'form-control', required: true, max: Date.today.strftime('%Y-%m-%d') %>
    </div>

    <!-- Campo de carga de imágenes -->
    <div class="mb-3">
      <%= form.label :foto, class: 'form-label' %>
      <%= form.file_field :foto, class: 'form-control', accept: 'image/*' %>

      <% if @perro_perdido.foto.present? %>
        <p class="mt-2">Imagen actual: <%= File.basename(@perro_perdido.foto.path) %></p>
      <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :edad, "Edad (en meses)", class: 'form-label' %>
      <%= form.number_field :edad, class: 'form-control', placeholder: 'Edad del perro', required: true, min: 1, id: 'edad_perro' %>
    </div>

    <div class="mb-3">
      <%= form.label :mail, "Correo de contacto", class: 'form-label' %>
      <%= form.email_field :mail, class: 'form-control', placeholder: 'Correo de contacto', required: true, id: 'mail_contacto' %>
    </div>

    <div class="text-center">
      <%= form.submit "Actualizar Perro Perdido", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/perros_perdidos/index.html.erb
<!-- app/views/perros_perdidos/index.html.erb -->
<div class="container text-center mt-5">
  <h1 class="mb-4">Perros Perdidos</h1>

  <% if current_user %>
    <%= link_to "Crear Publicación", new_perros_perdido_path, class: "btn btn-primary mb-4" %>
    <%= link_to "Mis Publicaciones", mis_publicaciones_perros_perdidos_path, class: "btn btn-primary mb-4" %>
  <% end %>

 <%= form_tag({ controller: 'perros_perdidos', action: 'filtrar' }, method: :get, class: "mb-3") do %>
  <div class="form-group row">
    <div class="col-sm-4 mx-auto">
      <%= label_tag "filter_raza", "Filtrar por Raza:" %>
      <%= select_tag "filter_raza", options_for_select(Raza.pluck(:nombre, :id), params[:filter_raza]), include_blank: 'Todas las razas', class: "form-control form-control-sm" %>
    </div>
  </div>
  <%= submit_tag "Filtrar", class: "btn btn-primary" %>
<% end %>

  <% if @perros_perdido.any? %>
    <div class="row">
      <% @perros_perdido.each do |perro_perdido| %>
        <div class="col-md-6 mb-4">
          <div class="card position-relative">
            <% if perro_perdido.foto? %>
              <%= image_tag perro_perdido.foto.url, class: "card-img-top w-100" %>
            <% else %>
              <!-- Puedes agregar un marcador de posición aquí o dejarlo en blanco -->
              <div class="placeholder-image"></div>
            <% end %>
           <% if (current_user && current_user.rol_id == 1) || (current_user && perro_perdido.user_id == current_user.id) %>
            <div class="dropdown position-absolute" style="top: 5px; right: 5px;">
              <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v"></i>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Editar", edit_perros_perdido_path(perro_perdido), class: "dropdown-item" %>
                <%= form_tag(perros_perdido_path(perro_perdido), method: :delete, class: 'perro-perdido-form') do %>
                  <%= submit_tag 'Eliminar', class: 'dropdown-item', onclick: "return confirm('¿Estás seguro de eliminar esta publicación?');" %>
                <% end %>

                <% if !(perro_perdido.encontrado) %>
                <%= form_for(perro_perdido, url: mark_found_perros_perdido_path(perro_perdido), method: :patch, class: 'perro-perdido-form') do |form| %>
                  <%= form.hidden_field :encontrado, value: true %>
                  <%= form.submit 'Marcar como encontrado', class: 'dropdown-item', onclick: "return confirm('¿Estás seguro de marcar como encontrado?');" %>
                <% end %>
                <% end %>
              </div>
            </div>
          <% end %>

            <div class="card-body">
              <h5 class="card-title"><strong>Se perdió: </strong><%= perro_perdido.nombre %></h5>
              <p class="card-text"><strong>Sexo:</strong> <%= perro_perdido.sexo %></p>
              <p class="card-text"><strong>Raza:</strong> <%= perro_perdido.raza.nombre %></p>
              <p class="card-text"><strong>Comportamiento:</strong> <%= perro_perdido.comportamiento %></p>
              <p class="card-text"><strong>Se perdió en:</strong> <%= perro_perdido.lugar %></p>
              <p class="card-text"><strong>Se vió por última vez el día:</strong> <%= perro_perdido.fecha.strftime("%d/%m/%Y") %></p>
              <p class="card-text"><strong>Edad (en meses):</strong> <%= perro_perdido.edad %></p>
              <% if (perro_perdido.encontrado) %>
              <h4 class="card-text"><strong> ¡¡ ENCONTRADO !! </strong></h4>
              <% end %>
              <% if !(current_user && perro_perdido.user_id == current_user.id) && !(perro_perdido.encontrado) %>
                <%= link_to "Contactar", contactar_propietario_path(id: perro_perdido.id), class: 'btn btn-success btn-block' %>
                <% end %>



            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No hay publicaciones de perros perdidos disponibles en este momento.</p>
  <% end %>
</div>

app/views/perros_perdidos/new.html.erb
<!-- app/views/perros_perdidos/new.html.erb -->
<div class="container mt-5">
  <h1 class="text-center">Crear Publicación de Perro Perdido</h1>

  <%= form_with(model: @perro_perdido, url: perros_perdidos_path, local: true, html: { class: 'my-4' }) do |form| %>
    <% if @perro_perdido.errors.any? %>
      <div id="error_explanation" class="text-center">
        <h2><%= pluralize(@perro_perdido.errors.count, "error") %> prohibited this publication from being saved:</h2>

        <ul>
          <% @perro_perdido.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @user_perros.present? %>
      <div class="mb-3">
        <%= form.label :user_perro, "Seleccionar Tu Perro", class: 'form-label' %>
        <%= form.select :user_perro, options_for_select(@user_perros.map { |perro| [perro.nombre, perro.id] }), { prompt: "Seleccionar Tu Perro" }, { class: "form-control", id: "user_perro", autocomplete: "off" } %>
      </div>
    <% end %>

    <!-- Campos ocultos para almacenar valores autocompletados -->
    <%= form.hidden_field :nombre, id: 'hidden_nombre_perro' %>
    <%= form.hidden_field :raza_id, id: 'hidden_raza_perro' %>
    <%= form.hidden_field :sexo, id: 'hidden_sexo_perro' %>
    <%= form.hidden_field :mail, id: 'hidden_mail_contacto' %>
    <%= form.hidden_field :edad, id: 'hidden_edad_perro' %>

    <div class="mb-3">
      <%= form.label :nombre, class: 'form-label' %>
      <%= form.text_field :nombre, class: 'form-control', placeholder: 'Nombre del perro', required: true, id: 'nombre_perro' %>
    </div>

    <div class="form-group">
      <%= form.label :sexo, class: "form-label" %>
      <%= form.select :sexo, ["Macho", "Hembra"], { prompt: "Seleccionar Sexo" }, { class: "form-control", id: "sexo_perro" } %>
    </div>

    <div class="mb-3">
      <%= form.label :raza_id, "Raza" %>
      <%= form.collection_select :raza_id, Raza.all, :id, :nombre, { prompt: "Seleccione una raza" }, class: "form-control", id: "raza_perro" %>
    </div>

    <div class="mb-3">
      <%= form.label :comportamiento, class: 'form-label' %>
      <%= form.text_area :comportamiento, class: 'form-control', placeholder: 'Comportamiento del perro', required: true %>
    </div>

    <div class="mb-3">
      <%= form.label :lugar, "Lugar donde se perdió el perro", class: 'form-label' %>
      <%= form.text_field :lugar, class: 'form-control', placeholder: 'Lugar donde se perdió el perro', required: true %>
    </div>

    <div class="mb-3">
      <%= form.label :fecha, "Ultima vez que se vió", class: 'form-label' %>
      <%= form.date_field :fecha, class: 'form-control', required: true, max: Date.today.strftime('%Y-%m-%d') %>
    </div>

    <div class="mb-3">
      <%= form.label :foto, "Imagen", class: 'form-label' %>
      <%= form.file_field :foto, class: 'form-control', accept: 'image/*', required: true %>
    </div>

    <div class="mb-3">
      <%= form.label :edad, "Edad (en meses)", class: 'form-label' %>
      <%= form.number_field :edad, class: 'form-control', placeholder: 'Edad del perro', required: true, min: 1, id: 'edad_perro' %>
    </div>

    <div class="mb-3">
      <%= form.label :mail, "Correo de contacto", class: 'form-label' %>
      <%= form.email_field :mail, class: 'form-control', placeholder: 'Correo de contacto', required: true, id: 'mail_contacto' %>
    </div>

    <%= form.hidden_field :tipo, value: 1 %>

    <div class="text-center">
      <%= form.submit "Publicar", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<!-- app/views/perros_perdidos/new.html.erb -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var perroSelect = document.getElementById('user_perro');
    var nombrePerroInput = document.getElementById('nombre_perro');
    var razaPerroInput = document.getElementById('raza_perro');
    var sexoPerroSelect = document.getElementById('sexo_perro');
    var edadPerroInput = document.getElementById('edad_perro');
    var perroDetails = <%= raw @perro_details.to_json %>;
    var mailContactoInput = document.getElementById('mail_contacto');
    var hiddenMailContactoInput = document.getElementById('hidden_mail_contacto');
    var hiddenEdadPerroInput = document.getElementById('hidden_edad_perro');

    if (perroSelect && nombrePerroInput && razaPerroInput && sexoPerroSelect && edadPerroInput && mailContactoInput && hiddenMailContactoInput && hiddenEdadPerroInput) {
      perroSelect.addEventListener('change', function() {
        var selectedPerroId = perroSelect.value;

        if (selectedPerroId === '') {
          // Si se selecciona "Seleccionar Perro", desbloquear y limpiar los campos
          nombrePerroInput.disabled = false;
          razaPerroInput.disabled = false;
          sexoPerroSelect.disabled = false;
          edadPerroInput.disabled = false;
          mailContactoInput.disabled = false;

          nombrePerroInput.value = '';
          razaPerroInput.value = '';
          sexoPerroSelect.value = '';
          edadPerroInput.value = '';
          mailContactoInput.value = '';
        } else {
          // Llenar los campos con la información del perro seleccionado
          var details = perroDetails[selectedPerroId];

          if (details) {
            // Establecer valores en campos ocultos
            hiddenMailContactoInput.value = '<%= current_user.email %>';
            hiddenEdadPerroInput.value = details.edad;
            document.getElementById('hidden_nombre_perro').value = details.nombre;
            document.getElementById('hidden_raza_perro').value = details.raza_id;
            document.getElementById('hidden_sexo_perro').value = details.sexo;

            // Deshabilitar los campos originales
            nombrePerroInput.disabled = true;
            razaPerroInput.disabled = true;
            sexoPerroSelect.disabled = true;
            edadPerroInput.disabled = true;
            mailContactoInput.disabled = true;

            // Establecer valores en campos visibles
            nombrePerroInput.value = details.nombre;
            razaPerroInput.value = details.raza_id;
            sexoPerroSelect.value = details.sexo;
            edadPerroInput.value = details.edad;
            mailContactoInput.value = '<%= current_user.email %>';


          }
        }
      });
    }
  });
</script>