config/routes.rb
Rails.application.routes.draw do
  get 'mis_turnos/index'
  get 'perros/new'
  get 'perros/create'
  get 'user_search/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :campaigns, except: [:show] do
    member do
      delete :destroy
      post :pay
      get :pay # Permite solicitudes GET para la acción pay
    end
    collection do
      get :search
    end
  end

  resources :perros_perdidos, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_perdidos#mis_publicaciones'
      get 'filtrar', to: 'perros_perdidos#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_perdidos#mark_found'
    end
  end


get 'contactar_propietario', to: 'perros_perdidos#contactar_propietario'
#post 'enviar_correo', to: 'perros_perdidos#enviar_correo'
post 'enviar_correo_perdido', to: 'perros_perdidos#enviar_correo_perdido'


get 'contactar_propietario_encontrado', to: 'perros_encontrados#contactar_propietario_encontrado'
post 'enviar_correo_encontrado', to: 'perros_encontrados#enviar_correo_encontrado'

  resources :perros_encontrados, except: [:show] do
    collection do
      get 'mis_publicaciones', to: 'perros_encontrados#mis_publicaciones'
      get 'filtrar', to: 'perros_encontrados#filtrar'  
    end
    member do
      patch 'mark_found', to: 'perros_encontrados#mark_found', as: :mark_found
    end
  end

  
  

  Rails.application.routes.draw do
  get 'mis_turnos/index'
    


    resources :historial_turnos do
      collection do
        get 'confirmados', to: 'historial_turnos#confirmados', as: :turnos_confirmados
        get 'pendientes', to: 'historial_turnos#pendientes', as: :turnos_pendientes
        get 'hoy', to: 'historial_turnos#hoy', as: :turnos_hoy
        put 'cancelar_turno'
      end
      member do
        put 'cancelar_turno'
        put 'agregar_horario'
        put 'agregar_texto'
        put 'agregar_consulta'
        post 'create_vaccine'
      end
    end

    
  end

  get 'historial_turno/mis_turnos', to: 'mis_turnos#index', as: 'mis_turnos'

  get '/users/:id/perros', to: 'user_search#perros', as: 'user_perros'    
  resources :historial_turnos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'dashboard/perros_perdidos'
  get 'dashboard/solicitar_turno'
  get 'servicios/cuidadores'
  get 'dashboard/perros_encontrados'
  get 'dashboard/adopciones'
  get 'dashboard/cruza_de_perros'
  get 'servicios/paseadores'  
  get 'dashboard/iniciar_sesion'
  get 'dashboard/mi_usuario'
  get 'dashboard/registrar_perro'
  get 'dashboard/registrar_usuario'
  get 'dashboard/modificar_usuario'
  get 'dashboard/eliminar_usuario'
  get 'dashboard/index'
  get '/perros/mis_perros'
  get '/users/search', to: 'user_search#search'
  get '/perros/registrar_perro', to: 'perros#new', as: 'registrar_perro'
  get 'cruza/cruza'
  get 'cruza/publicar'
  get 'cruza/eliminar_perro'

  Rails.application.routes.draw do
    get 'eliminar_perro', to: 'cruza#eliminar_perro'
    delete 'eliminar_perro', to: 'cruza#destroy_perro_cruza'
    get 'cruza', to: 'cruza#cruza'
    get 'publicar', to: 'cruza#publicar'
    get 'mis_perros_cruza', to: 'cruza#mis_perros_cruza'
    get 'mis_perros_cruzados', to: 'cruza#mis_perros_cruzados'
  
    resources :cruza, only: [:destroy] do
      member do
        get 'contactar'
        delete 'destroy'
      end
    
      collection do
        post 'publicar', to: 'cruza#publicar', as: 'publicar'
      end
    end
  end


  get 'perros/editar_perro'
  get 'cargar_cuidador', to: 'servicios#cargar_cuidador', as: :cargar_cuidador
  get 'cargar_paseador', to: 'servicios#cargar_paseador', as: :cargar_paseador
  post '/guardar_cuidador', to: 'servicios#guardar_cuidador'
  post '/guardar_paseador', to: 'servicios#guardar_paseador'

  match '/enviar_correo', to: 'servicios#enviar_correo', via: [:post, :delete]


  get '/paseadores', to: 'servicios#paseadores', as: 'paseadores'
  get '/cuidadores', to: 'servicios#cuidadores', as: 'cuidadores'


  resources :servicios, except: [:show] do
    member do
      get 'edit'   # Página de edición
      patch 'actualizar_servicio'   # Acción de actualización
      delete 'destroy'  # Nueva acción para eliminar
    end
  end
resources :perros

  get 'mis_perros', to: 'perros#mis_perros', as: 'mis_perros'

  # config/routes.rb

  # config/routes.rb

  resources :usuarios, controller: 'dashboard', only: [] do
    member do
      patch :eliminar
    end
  end

  devise_scope :user do
    get 'users/edit_password', to: 'users/registrations#edit_password', as: 'edit_password_user'
    put 'users/update_password', to: 'users/registrations#update_password', as: 'update_password_user'
  end

  resources :user_search, only: [] do
    collection do
      get 'search'
    end
  end

  root "dashboard#index"


end

app/views/layouts/application.html.erb
    <!DOCTYPE html>
<html>
  <head>

    <!-- Incluye Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<!-- Incluye jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<!-- Incluye Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>

<!-- Incluye Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>Ohmydog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

  </head>

  <body id="page-top">
    <!-- Script para mostrar la alerta en una ventana emergente del navegador -->
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        const alertMessage = "<%= j(alert) %>"; // j() es un método de Rails para escapar el contenido JS
        const noticeMessage = "<%= j(notice) %>"; // j() es un método de Rails para escapar el contenido JS
  
        // Mostrar la alerta en una ventana emergente del navegador
        if (alertMessage) {
          alert(alertMessage);
        } else if (noticeMessage) {
          alert(noticeMessage);
        }
      });
    </script>
  
    <!-- Resto de tu contenido HTML -->
  </body>
  

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
           <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">  

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/dashboard/index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i><img src="<%= asset_path('logo.png') %>"style="max-width: 100px; max-height: 100px;"></i>
                </div>
                <div class="sidebar-brand-text mx-2">Oh My Dog </div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0"> 

            <!-- Nav Item - Usuarios Collapse Menu -->
           <% if user_signed_in? && current_user.rol_id == 1 %>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePagesUsuarios" aria-expanded="true" aria-controls="collapsePagesUsuarios">
                    <img src="<%= asset_path('usuarios.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                    <span>Gestión de Usuarios</span>
                </a>
                <div id="collapsePagesUsuarios" class="collapse" aria-labelledby="headingPagesUsuarios" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="/users/sign_up">Registrar Usuario</a>
                        <a class="collapse-item" href="/dashboard/eliminar_usuario.html">Eliminar Usuario</a>
                        <a class="collapse-item" href="/perros/registrar_perro">Cargar Perro</a>
                        <a class="collapse-item" href="/users/search">Buscar Usuario</a>
                    </div>
                </div>
            </li>
            <% end %>

            <% if user_signed_in? && current_user.rol_id == 1 %>
            <li class="nav-item">

                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePagesTurnos" aria-expanded="true" aria-controls="collapsePagesTurnos">
                    <img src="<%= asset_path('turno.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                    <span>Gestión de Turnos</span>
                </a>
                <div id="collapsePagesTurnos" class="collapse" aria-labelledby="headingPagesTurnos" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="/historial_turnos/pendientes.html">Turnos pendientes</a>
                        <a class="collapse-item" href="/historial_turnos/confirmados.html">Turnos confirmados</a> 
                        <a class="collapse-item" href="/historial_turnos/hoy.html">Turnos de hoy</a>                    
                   
                    </div>
                </div>         
                </li>
        <% end %>
        

        <% if user_signed_in? && current_user.rol_id == 2 %>
            <li class="nav-item">
            <a class="nav-link" href="<%= new_historial_turno_path %>" style="display: flex; align-items: center;"> 
            <img src="<%= asset_path('turno.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
            <span>Solicitar Turno</span>
             </a>     

        <% end %>


        <li class="nav-item">
        <%= link_to perros_perdidos_path, class: 'nav-link', style: 'display: flex; align-items: center;' do %>
            <img src="<%= asset_path('perro.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
            <span>Perros Perdidos</span>
        <% end %>
        </li>

        <li class="nav-item">
        <%= link_to perros_encontrados_path, class: 'nav-link', style: 'display: flex; align-items: center;' do %>
            <img src="<%= asset_path('perro.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
            <span>Perros Encontrados</span>
        <% end %>
        </li>


        <li class="nav-item">
            <%= link_to campaigns_path, class: 'nav-link', style: 'display: flex; align-items: center;', disabled: true do %>
            <img src="<%= asset_path('donacion.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
            <span>Campañas de Donación</span>
            <% end %>
                </li>


            
           <!-- <li class="nav-item">
                <a class="nav-link" href="/dashboard/adopciones.html" style="display: flex; align-items: center;">
                    <img src="<%= asset_path('adopcion.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                    <span>Adopciones</span>
                </a>
            </li> -->
        
        <li class="nav-item">
            <a class="nav-link" href="/servicios/paseadores.html" style="display: flex; align-items: center;">
                <img src="<%= asset_path('paseador.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                <span>Paseadores</span>
            </a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="/servicios/cuidadores.html" style="display: flex; align-items: center;">
                <img src="<%= asset_path('cuidador.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                <span>Cuidadores</span>
            </a>
        </li>


        <% if user_signed_in? && current_user.rol_id == 2 %>
                <li class="nav-item">
                        <a class="nav-link" href="/cruza/cruza.html" style="display: flex; align-items: center;">
                            <img src="<%= asset_path('cruza.png') %>" style="max-width: 20px; max-height: 20px; margin-right: 10px;">
                            <span>Cruza de Perros</span>
                        </a>
                    </li>
            <% end %>
            
        
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">  
            
            <div class="sidebar-contact" style="color: white; padding: 10px;">
                <a style="display: flex; align-items: center;">
                    <span>ohmydog@veterinaria.com</span>
                    </a>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">

               <!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
        </li>

        <!-- Nav Item - User Information -->
        <% if user_signed_in? %>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                        <%= current_user.nombre %>
                        <% if current_user.apellido.present? %>
                            <%= current_user.apellido %>
                        <% end %>
                    </span>
                    <img class="img-profile rounded-circle" src="/assets/usuarioGenerico.png">
                </a>

                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <!-- Opciones para usuarios autenticados -->
                    
                    
                    <a class="dropdown-item" href="/users/edit">
                        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                        Mis Datos
                    </a>

                    <a class="dropdown-item" href="<%= mis_turnos_path %>">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Mis Turnos
                    </a>

                    <a class="dropdown-item" href="/perros/mis_perros.html">
                    <i class="fas fa-dog fa-sm fa-fw mr-2 text-gray-400"></i>
                    Editar a mis Perros
                     </a>

                   <a class="dropdown-item" href="<%= edit_password_user_path %>">
                   <i class="fas fa-lock fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cambiar Contraseña
                     </a>

                    <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete" data-confirm="¿Estás seguro?">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Cerrar Sesión
                    </a>
                </div>
            </li>
        <% else %>
            <!-- Opciones para usuarios no autenticados -->
            <li class="nav-item">
                <a class="nav-link" href="<%= new_user_session_path %>">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                        Iniciar Sesión
                    </span>
                    <img class="img-profile rounded-circle" src="/assets/usuarioGenerico.png">
                </a>
            </li>
        <% end %>
    </ul>
    <!-- End of Topbar -->
</nav>

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <%= yield %>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Desarrollado por: SoftDeliver &copy; 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>
<style>
  body {
    background-color: #000000; /* Cambia el color de fondo a azul claro */
  }
</style>

</html>